name: Build Dylib
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # تحديث للإصدار 4
        with:
          submodules: true

      - name: Setup Theos
        uses: pypush/actions-setup-theos@v1.1 # تحديث الإصدار

      - name: Build Tweak
        run: |
          cd template
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # تحديث للإصدار 4 (حل المشكلة الأساسية)
        with:
          name: MyModDylib
          path: template/.theos/obj/debug/*.dylib
